### PR TITLE
Add "trail" interpolation for sized lines.

### PR DESCRIPTION
**Pull request by jheer**
This PR adds a new `interpolate` option for `line` marks, currently named `"trail"`. The trail interpolator behaves similar to `"linear"` interpolation, except that it also reads the `size` property of scenegraph items in order to dynamically change the line (or trail) width along the path. Each line segment is drawn as a closed path segment with rounded edges.

While useful, `"trail"` interpolation does have some differences from standard `line` marks. First, to fully color the mark, a `fillColor` must be provided. For all other `line` mark types, the `fillColor` fills in the hull of the line (not the stroke). Second, `"trail"` interpolation requires a `size` property, which no other `line` types use.

So, some design questions remain:
1. Should `"trail"` interpolation remain an option for `line` marks? Or, should it be an interpolation option for `area` marks instead? Areas have more similar fill/stroke semantics and we might consider using a property other than size (e.g., `width`, which areas already support) to set the trail width.
2. Is `"trail"` an appropriate name? What other names should we consider?
3. Any other thoughts?

### CODE REVIEW

**Comment by jheer** [comment]
@arvind @kanitw @domoritz Please chime in if you have any opinions on the questions above. This work should allow us to eventually support variably-sized line marks in Vega-Lite, but I'm not sure which design decisions might be the most conducive to the VL compiler. (For example, is it easy enough to swap between different _Vega_ mark types within a higher-level _Vega-Lite_ mark type?)

**Comment by jheer** [comment]
I've gone ahead and merged this, but have no problem revisiting this later. Please take a look and share any comments.

**Comment by domoritz** [comment]
I was a bit surprised that trail is an interpolation option. Is it because you didn't want to implement different interpolation methods for variable width lines?

If variable width lines behave exactly the same as lines if the width is set to a fixed value, I think it makes sense to use the same mark type for both. However, if they don't (and I'm reading your comments as thought they do not), I think it should become its own mark type. If variable width lines are its own mark type, compared to lines it wouldn't support interpolation and support `fillColor` and require `size`. 

> is it easy enough to swap between different Vega mark types within a higher-level Vega-Lite mark type?

I don't think this would be an issue.

**Comment by arvind** [comment]
Apologies for not weighing in sooner. My vote would be to set this as an interpolation option for area marks given the additional fill/stroke semantics that can/should be specified. This would make it more feasible for a user to iterate through the various interpolation options to evaluate the difference (versus, with line marks, switching to/from `trail` would require adding/removing properties). For instance, only one property in the following snippet would need to be modified to generate the test case. 

``` json
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 10, "y": 144, "size": 8},
        {"x": 50, "y": 90,  "size": 12},
        {"x":100, "y": 114, "size": 16},
        {"x":150, "y": 18,  "size": 14}
      ]
    }
  ],
  "marks": [
    {
      "type": "area",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "interpolate": {"value": "linear"},
          "x": {"scale": "x", "field": "x"},
          "y": {"scale": "y", "field": "y"},
          "height": {"field": "size"},
          "fill": {"value": "steelblue"},
          "stroke": {"value": "lightsalmon"}
        }
      }
    }
  ]
```

**Comment by arvind** [comment]
If we were to stick with `trail` on line marks (or if we were to say that line marks supported `trail` interpolation along with area marks which would be my preference), my intuition would be that line marks would continue to only respect stroke color, and the size of the trail would be determined by stroke width.

**Comment by jheer** [comment]
Thanks for the input! In 48c8b530cead59a1cbe4d6148b25b49eae228eaa I updated the design to use an `area` mark instead, given the better semantic match. For the trail size, either the `width` or `height` property can be used (in that precedence order). If neither are specified the size currently defaults to 1. 

Whether or not to also support trail interpolation for line marks with restricted stroke properties can be re-visited as needed in the future.

To @domoritz's question, I think it is reasonable to incorporate this feature as an interpolation option because we do not support variable-width lines for any interpolation style other than linear. I did spend a small amount of time looking into possible ways to produce variable-width lines by consuming the output of an arbitrary interpolator, but at minimum this would require a new code path for appropriate linear subdivision of cubic bezier curves, and the resulting output paths for such curves would likely incur high rendering overhead. I'm not convinced the costs justify the benefits.

The `interpolate` method name currently remains `"trail"`. I'm fine with that, but if you have any alternative names to consider, please share.

**Pull request merged**
